sistemahorista/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from sistemahorista.sistem_views.dependente_views import CadastrarDependente, AtualizarDependente, DeletarDependente
from sistemahorista.sistem_views.funcionario_views import (
    ListarFuncionarios, CadastrarFuncionario, AtualizarFuncionario, DeletarFuncionario, Funcionario_detalhe)
from sistemahorista.sistem_views.salario_views import CadastrarSalario, AtualizarSalario, DeletarSalario
from sistemahorista.sistem_views.user_views import Cadastro_usuario, ListarUsuario, AtualizarUsuario, DeletarUsuario
from sistemahorista.views import Login, Logout, paginainicial, Busca,fibonacci,receber_array

app_name = 'sistemahorista'
urlpatterns = [
    # <______________________________Urls de suporte_____________________________________________>#
    path('', Login.as_view(), name='login_sistema'),
    path('logout/', Logout.as_view(), name='logout_sistema'),
    path('telainicial/', paginainicial, name='tela_inicial'),

    path('busca', Busca.as_view(), name='busca_dinamica'),
    path('fibonacci/', fibonacci, name='fibonacci'),
    path('receber_array/', receber_array, name='receber_array '),

# <______________________________Urls de usuario_____________________________________________>#

    path('cadastro_usuario/', Cadastro_usuario.as_view(), name='cadastro_usuario'),
    path('tabela_usuarios', ListarUsuario.as_view(), name='tabela_usuarios'),
    path('tabela_usuarios/<int:pk>/atualizar_usuario/', AtualizarUsuario.as_view(), name='atualizar_usuario'),
    path('tabela_usuarios/<int:pk>/deletar_usuario/', DeletarUsuario.as_view(), name='deletar_usuario'),
 # <______________________________Urls de Funcionarios_____________________________________________>#

    path('tabela_funcionarios', ListarFuncionarios.as_view(), name='tabela_funcionarios'),
    path('cadastro_funcionario/', CadastrarFuncionario.as_view(), name='cadastro_funcionario'),
    path('tabela_usuarios/<int:pk>/atualizar_funcionario/',
         AtualizarFuncionario.as_view(), name='atualizar_funcionario'),
    path('tabela_usuarios/<int:pk>/deletar_funcionario/',
         DeletarFuncionario.as_view(), name='deletar_funcionario'),
    path('tabela_usuarios/<int:pk>/ficha_funcionario/',
         Funcionario_detalhe.as_view(), name='detalhe_funcionario'),

# <______________________________Urls de Dependente_____________________________________________>#

    path('tabela_usuarios/<int:pk>/cadastro_dependente/',
         CadastrarDependente.as_view(), name='cadastrar_dependente'),

    path('tabela_usuarios/<int:pk>/atualizar_dependente/',
         AtualizarDependente.as_view(), name='atualizar_dependente'),
    path('tabela_usuarios/<int:func_pk>/deletar_dependente/<int:pk>',
         DeletarDependente.as_view(), name='deletar_dependente'),

# <______________________________Urls de Salario_____________________________________________>#

    path('tabela_usuarios/<int:pk>/cadastro_salario/',
         CadastrarSalario.as_view(), name='cadastrar_salario'),

    path('tabela_usuarios/<int:pk>/atualizar_salario/',
         AtualizarSalario.as_view(), name='atualizar_salario'),
    path('tabela_usuarios/<int:func_pk>/deletar_salario/<int:pk>',
         DeletarSalario.as_view(), name='deletar_salario'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistemarh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sistemahorista.urls')),
    path('admin/', admin.site.urls,name='index'),

]

sistemahorista/forms.py
from django import forms
from django.contrib.auth import get_user_model
from.models import Salario,Funcionario,DependenteElegivel
from decimal import Decimal



User=get_user_model()

class UsuarioForm(forms.ModelForm):
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UsuarioForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['username'].required = False
            self.fields['password'].required = False

    def clean(self):
        cleaned_data = super().clean()
        username_data = cleaned_data.get('username')
        password_data = cleaned_data.get('password')
        email_data = cleaned_data.get('email')

        if not self.instance.pk:
            if not password_data:
                self.add_error(
                    'password',
                    'Preenchimento de senha obrigatorio para cadastro de novos usuarios'
                )

            if not username_data:
                self.add_error('username',
                               'Preenchimento de nome de usuario obrigatorio para cadastro de novos usuarios')
        if password_data and len(password_data) < 6:
            self.add_error('password',
                           'Senha deve ter no minimo 6 caracteres')


        usuario_db=User.objects.none()
        if username_data:
            usuario_db = User.objects.filter(
                username__iexact=username_data
            )

        email_db = User.objects.none()
        if email_data:
            email_db = User.objects.filter(
                email__iexact=email_data
            )


        if self.instance.pk:
            usuario_db = usuario_db.exclude(pk=self.instance.pk)
            email_db = email_db.exclude(pk=self.instance.pk)

        if usuario_db.exists():
            self.add_error(
                'username',
                f'o usuario {username_data} ja existe no banco de dados'
            )
        if email_db.exists():
            self.add_error(
                'email',
                f'o email {email_data} ja existe no banco de dados'
            )

        return cleaned_data

class FuncionarioForm(forms.ModelForm):
    nome_funcionario = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    salario_hora = forms.DecimalField(max_digits=10, decimal_places=2, required=True,
                                      widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Funcionario
        fields = ['nome_funcionario', 'salario_hora']

    def __init__(self,*args,**kwargs):
        super(FuncionarioForm, self).__init__(*args,**kwargs)
        if self.instance and self.instance.pk:
            self.fields['nome_funcionario'].required = False
            self.fields['salario_hora'].required = True

    def clean(self):
        cleaned_data = super().clean()
        nome_funcionario_data = cleaned_data.get('nome_funcionario')
        salario_hora_data = cleaned_data.get('salario_hora')


        if not self.instance.pk:
            if not nome_funcionario_data:
                self.add_error(
                    'nome_funcionario',
                    'Preenchimento obrigatorio do nome do funcionario'
                )

            if not salario_hora_data:
                self.add_error('salario_hora',
                               'Preenchimento obrigatorio  do salario-hora do funcionario')
        if salario_hora_data <0.00:
            self.add_error('salario_hora',
                           'Digite o salario corretamente, valor negativo')


        if salario_hora_data is not None and  not isinstance(salario_hora_data,(int,float,Decimal)):
            self.add_error('salario_hora',
                           'Digite um valor correto')


        return cleaned_data

class DependenteElegivelForm(forms.ModelForm):

    responsavel_pelo_dependente=forms.CharField(
        label='Responsavel pelo dependente',
        required=False,
        widget=forms.TextInput(
            attrs={
                'readonly':'readonly',
                'class':'form-control'
            }
        )
    )


    nome_dependente = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    idade = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = DependenteElegivel
        fields = ['responsavel','nome_dependente', 'idade']

    def __init__(self, *args, **kwargs):
        self.responsavel_instance = kwargs.pop('responsavel_instance', None)
        super(DependenteElegivelForm, self).__init__(*args, **kwargs)
        self.fields['responsavel'].widget = forms.HiddenInput()
        self.fields['responsavel'].required = True

        funcionario_obj = None

        if self.responsavel_instance:

            funcionario_obj = self.responsavel_instance
        elif self.instance and self.instance.pk:

            funcionario_obj = self.instance.responsavel


            self.fields['nome_dependente'].required = False
            self.fields['idade'].required = False

        if funcionario_obj:

            self.fields['responsavel_pelo_dependente'].initial = funcionario_obj.nome_funcionario
            self.fields['responsavel'].initial = funcionario_obj.pk

    def clean(self):
        cleaned_data = super().clean()
        idade_dependente_data = cleaned_data.get('idade')


        if idade_dependente_data is not None and idade_dependente_data >14:
            self.add_error('idade','Somente dependentes com menos de 14 anos podem ser cadastrados')
        return cleaned_data






class SalarioForm(forms.ModelForm):

    funcionario_nome=forms.CharField(
        label='Funcionario',
        required=False,
        widget=forms.TextInput(
            attrs={
                'readonly':'readonly',
                'class':'form-control'
            }
        )
    )


    quantidade_horas_trabalhadas=forms.IntegerField(
        required=True,
        widget=forms.NumberInput(attrs={'class':'form-control'})
    )

    class Meta:
        model = Salario
        fields = ['funcionario','quantidade_horas_trabalhadas']

    def __init__(self,*args,**kwargs):

        self.funcionario_instance=kwargs.pop('funcionario_instance',None)


        super(SalarioForm, self).__init__(*args,**kwargs)
        self.fields['funcionario'].widget=forms.HiddenInput()
        self.fields['funcionario'].required=True

        funcionario_obj=None

        if self.funcionario_instance:
            funcionario_obj=self.funcionario_instance
        elif self.instance and self.instance.pk:
            funcionario_obj=self.instance.funcionario

            self.fields['quantidade_horas_trabalhadas'].required=False


        if funcionario_obj:
            self.fields['funcionario_nome'].initial=funcionario_obj.nome_funcionario
            self.fields['funcionario'].initial=funcionario_obj.pk

sistemahorista/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.contrib.auth import  logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.list import View,ListView
from django.shortcuts import redirect,render
from django.views.generic.edit import DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from datetime import date,timedelta
from django.core.paginator import Paginator
from django.db.models import F, FloatField, ExpressionWrapper,Prefetch,DateField,Func,Case,When,Value,IntegerField
from sistemahorista.services.main_services import MainServices
from sistemahorista.services.search_map import mapa_modelos
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from sistemahorista.teste2_esboco import fibonacci_teste2




# Create your views here.

#<______________________________views de suporte_____________________________________________>#

class Login(LoginView):
    template_name = 'sistemahorista/login.html'
    success_url = reverse_lazy('sistemahorista:tela_inicial')
    redirect_authenticated_user = True

    def get_success_url(self):
        return self.success_url

    def form_valid(self, form):
        messages.success(self.request,f'usuario {form.get_user().username} logado com sucesso')
        return super().form_valid(form)

    def form_invalid(self, form):
        usuario_ativo=form.get_user().is_active
        senha_valida=form.get_user().check_password(form.data['password'])
        if not usuario_ativo:
            messages.warning(self.request, f'Usuario ainda nao esta ativo no sistema, procure o administrador')

        if not senha_valida:
            messages.warning(self.request, f'Senha Invalida')

        return super().form_invalid(form)

class Logout(LoginRequiredMixin,View):

    def get(self,*args,**kwargs):
        logout(self.request)
        return redirect('sistemahorista:login_sistema')


class Busca(LoginRequiredMixin,View):

    def get(self, request):
        termo=request.GET.get('q','').strip()
        resultados={}
        if termo:
            for modelo_nome,info in mapa_modelos.items():
                queryset=info['queryset']
                campos=info['campos']
                qs_resultados=MainServices.busca_centralizada(queryset,termo,campos)

                if qs_resultados.exists():
                    resultados[modelo_nome]=qs_resultados


        return render(request, f'sistemahorista/busca.html', {
            'termo': termo,
            'resultados': resultados,
        })

@login_required()
def paginainicial(request):
    return render(request, 'sistemahorista/tela_inicial_vazia.html')


@login_required()
def fibonacci(request):
    esta_na_sequencia=False
    limite_sequencia_fibonacci=None
    sequencia = []
    if request.method=='POST':
       try:
           limite_sequencia_fibonacci = int(request.POST.get('numero'))
           sequencia=fibonacci_teste2(limite_sequencia_fibonacci)
       except ValueError as e:
           sequencia=[f'erro{e}']
           esta_na_sequencia = False
    if limite_sequencia_fibonacci in sequencia:
        esta_na_sequencia = True
    contexto={
        'resultado_sequencia':sequencia,
        'numero_na_sequencia': esta_na_sequencia,
         'numero_digitado':limite_sequencia_fibonacci
    }
    return render(request,'sistemahorista/fibonacci.html',contexto)


@login_required()
def receber_array(request):
    contexto = {
        'etapa': 1,
        'tamanho_alvo': None,
        'erro_mensagem': None
    }
    tamanho_alvo = request.session.get('tamanho_alvo')
    if tamanho_alvo is not None:
        contexto['tamanho_alvo'] = tamanho_alvo
        contexto['etapa'] = 2
    if request.method == 'POST':
        if 'tamanho_sequencia' in request.POST:
            try:
                N = int(request.POST.get('tamanho_sequencia'))
                if N <= 0:
                    raise ValidationError('O tamanho da sequencia deve ser maior que 0(zero)')
                request.session['tamanho_alvo'] = N
                contexto['tamanho_alvo'] = N
                contexto['etapa'] = 2

            except (ValidationError, ValueError) as e:
                contexto['erro_mensagem'] = str(e)
                contexto['etapa'] = 1
            return render(request, 'sistemahorista/exercicio2_sequencia.html', contexto)

        elif 'valores_da_sequencia' in request.POST and tamanho_alvo is not None:
            entrada_string = request.POST.get('valores_da_sequencia', '')
            try:
                valores_completos = [
                    int(v.strip()) for v in entrada_string.split(',') if v.strip()
                ]
                if not valores_completos:
                    raise ValidationError('Nenhum valor inserido')

                sequencia_a_processar = valores_completos[:tamanho_alvo]

                if len(sequencia_a_processar) < tamanho_alvo:
                    contexto['aviso'] = (f'Apenas {len(sequencia_a_processar)} números foram '
                                         f'processados, em vez dos {tamanho_alvo} esperados')
                if not sequencia_a_processar:
                    raise ValidationError('A sequência final está vazia.')

                minimo_valor_sequencia = min(sequencia_a_processar)
                segundo_maior=sorted(sequencia_a_processar)
                segundo_maior=segundo_maior[-2]
                maximo_valor_sequencia = max(sequencia_a_processar)
                contexto['etapa'] = 3
                contexto['resultado_sequencia'] = sequencia_a_processar
                contexto['segundo_maior_valor'] = segundo_maior
                contexto['menor_valor'] = minimo_valor_sequencia
                contexto['maior_valor'] = maximo_valor_sequencia
                contexto['tamanho_final'] = len(sequencia_a_processar)
                if 'tamanho_alvo' in request.session:
                    del request.session['tamanho_alvo']
            except (ValidationError, ValueError) as e:
                contexto['erro_mensagem'] = str(e)
                contexto['etapa'] = 2

            return render(request, 'sistemahorista/exercicio2_sequencia.html', contexto)

    if 'tamanho_alvo' in request.session:
        del request.session['tamanho_alvo']

    return render(request, 'sistemahorista/exercicio2_sequencia.html', contexto)

sistemahorista/templates/sistemahorista/fichafuncionario.html
{% extends "global/base.html" %}


{% block content %}
    <div class="detalhes-membro">
        <h2>Detalhes do funcionario</h2>

        <div class="linha-detalhe">
            <span class="campo-label">Funcionario:</span>
            <span class="campo-valor">{{ funcionario.nome_funcionario }}</span>
        </div>
        <div class="linha-detalhe">
            <span class="campo-label">Salario-Hora:</span>
            <span class="campo-valor">{{ funcionario.salario_hora }} </span>
        </div>

        <div class="linha-detalhe">
            <span class="campo-label">dependentes:</span>
            <span class="campo-valor">{{ funcionario.dependenteelegivel.count }}</span>
        </div>


        <div class="botoes-acao-duas-colunas">
            <a class=" btn btn-editar" href="{% url 'sistemahorista:atualizar_funcionario' funcionario.pk %}">Editar</a>
            <a onclick="return abrir_popup_dependente(this.href)" class="btn btn-editar"
               href="{% url 'sistemahorista:cadastrar_salario' funcionario.pk %}">Cadastrar Salario</a>
            <a onclick="return abrir_popup_dependente(this.href)" class="btn btn-editar"
               href="{% url 'sistemahorista:cadastrar_dependente' funcionario.pk %}">Cadastrar dependente</a>
            <form method="post"
                  class="form-excluir"
                  action="{% url 'sistemahorista:deletar_funcionario' funcionario.pk %}"
                  onsubmit="if(confirm('Deseja realmente excluir este produto?')) { this.querySelector('button').disabled = true; return true; } else { return false; }">
                {% csrf_token %}
                <button type="submit" class="btn btn-excluir">Excluir</button>
            </form>

        </div>
        <a class="btn btn-voltar" href="{% url 'sistemahorista:tabela_funcionarios' %}">← Voltar para lista</a>
    </div>

    <div>
        <div class="list-container">
            <h2>Salarios pagos ao funcionario</h2>

            <!-- Ordenação -->
            <form method="get" class="ordenacao-grid" id="form-ordenacao">

                <div class="grupo-ordenacao">
                    <strong>Líquido</strong>
                    <label><input type="radio" name="campo" value="liquido"
                                  {% if request.GET.campo == 'liquido' %}checked{% endif %}> Liq.</label>
                </div>

                <div class="grupo-ordenacao">
                    <strong>Bruto</strong>
                    <label><input type="radio" name="campo" value="bruto"
                                  {% if request.GET.campo == 'bruto' %}checked{% endif %}> Bruto</label>
                </div>

                <div class="grupo-ordenacao">
                    <strong>Ordem</strong>
                    <label><input type="radio" name="ordem" value="asc"
                                  {% if request.GET.ordem == 'asc' %}checked{% endif %}> ↑ Menor</label>
                    <label><input type="radio" name="ordem" value="dec"
                                  {% if request.GET.ordem == 'dec' %}checked{% endif %}> ↓ Maior</label>
                </div>

                <div class="grupo-ordenacao ordenar-btn">
                    <button type="submit" class="btn-ordenar">Ordenar</button>
                </div>
            </form>
            <!-- Tabela de vendas -->
            <table class="list-table">
                <thead>
                <tr>
                    <th>Id-Salario</th>
                    <th>Horas Trabalhadas</th>
                    <th>Salario Bruto</th>
                    <th>Salario Liquido</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for salario in salarios %}
                    <tr>
                        <td data-label="id">
                            {{ salario.pk }}
                        </td>

                        <td data-label="horas trabalhadas">{{ salario.quantidade_horas_trabalhadas }}</td>
                        <td data-label="Salario Bruto">{{ salario.salario_bruto }}</td>
                        <td data-label="Salario Liquido">{{ salario.salario_liquido }}</td>


                        <td data-label="Ações">
                            <div class="action-buttons">
                                <a onclick="return abrir_popup_dependente(this.href)"
                                   href="{% url 'sistemahorista:atualizar_salario'  salario.pk %}"
                                   class="edit">Editar</a>
                                <form method="post"
                                      class="form-excluir"
                                      action="{% url 'sistemahorista:deletar_salario'  funcionario.pk salario.pk %}"
                                      onsubmit="if(confirm('Deseja realmente excluir este produto?')) { this.querySelector('button').disabled = true; return true; } else { return false; }">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-excluir">Excluir</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7">Nenhuma salario registrado.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="pagination" style="font-size: 20px;">
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Primeira</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}

                    <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>

    </div>

    <div>
        <div class="list-container">
            <h2>Lista de Dependentes funcionario</h2>


            <table class="list-table">
                <thead>
                <tr>
                    <th>Id-Dependentes</th>
                    <th>Nome do dependente</th>
                    <th>idade do dependente</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for dependente in dependentes %}
                    <tr>
                        <td data-label="id">
                            {{ dependente.pk }}
                        </td>

                        <td data-label="Nome Do dependente">{{ dependente.nome_dependente }}</td>
                        <td data-label="idade do dependente">{{ dependente.idade }}</td>


                        <td data-label="Ações">
                            <div class="action-buttons">
                                <a onclick="return abrir_popup_dependente(this.href)"
                                   href="{% url 'sistemahorista:atualizar_dependente' dependente.pk %}" class="edit">Editar</a>
                                <form method="post"
                                      class="form-excluir"
                                      action="{% url 'sistemahorista:deletar_dependente'  funcionario.pk dependente.pk %}"
                                      onsubmit="if(confirm('Deseja realmente excluir este produto?')) { this.querySelector('button').disabled = true; return true; } else { return false; }">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-excluir">Excluir</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7">Nenhuma dependente registrado.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="pagination" style="font-size: 20px;">
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Primeira</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}

                    <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>

    </div>


    <!-- Script de controle de ordenação -->
    <script>
        document.getElementById('form-ordenacao').addEventListener('submit', function (event) {
        event.preventDefault();

        const form = event.target;
        const params = new URLSearchParams(window.location.search); // Mantém paginação/filtros existentes

        // 1. Capturar o CAMPO e a ORDEM selecionados
        const campo = form.querySelector('input[name="campo"]:checked');
        const ordem = form.querySelector('input[name="ordem"]:checked');

        // 2. Limpar os parâmetros de ordenação antigos, se existirem
        params.delete('campo');
        params.delete('ordem');

        // 3. Adicionar os novos parâmetros
        if (campo) {
            params.append('campo', campo.value);
        }
        if (ordem) {
            params.append('ordem', ordem.value);
        }


        const url = window.location.pathname + '?' + params.toString();
        window.location.href = url;
    });


        function abrir_popup_dependente(url) {
            const largura = 600;
            const altura = 400;
            const esquerda = (screen.width / 2) - (largura / 2);
            const topo = (screen.height / 2) - (altura / 2);

            const popup = window.open(
                url,
                'PopUpDependente',
                `width=${largura},height=${altura},top=${topo},left=${esquerda}`
            );

            const timer = setInterval(
                function () {
                    if (popup.closed) {
                        clearInterval(timer);
                        window.location.reload();
                    }

                }, 500
            );
            return false;

            function fecharPopUpdependente() {
                window.opener.location.reload(true);
                window.close();
            }


        }
    </script>



{% endblock %}

sistemahorista/templates/sistemahorista/tabela_funcionario.html
{% extends "global/base.html" %}
{% load static %}

{% block content %}
    <div class="list-container">
        <h2>Funcionarios cadastrados</h2>
        <table class="list-table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Funcionario</th>
                <th>Salario-Hora</th>
                <th>dependentes</th>
                <th>Ações</th>


            </tr>
            </thead>
            <tbody>
            {% for funcionario in funcionarios  %}
                <tr>
                    <td data-label="ID">
                        <a href="{% url 'sistemahorista:detalhe_funcionario' funcionario.pk %}" class="edit">
                            {{ funcionario.pk }}</a>


                    </td>
                    <td data-label="Usuário">{{ funcionario.nome_funcionario }}</td>
                    <td data-label="Salario-Hora">{{ funcionario.salario_hora }}</td>
                    <td data-label="dependentes">{{ funcionario.dependenteelegivel.count }}
                    <td data-label="Ações">
                        <div class="action-buttons">
                            <a href="{% url 'sistemahorista:atualizar_funcionario' funcionario.pk %}" class="edit">Editar</a>
                            <form method="post"
                                  class="form-excluir"
                                  action="{% url 'sistemahorista:deletar_funcionario' funcionario.pk %}"
                                  onsubmit="if(confirm('Deseja realmente excluir este Usuario?')) { this.querySelector('button').disabled = true; return true; } else { return false; }">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-excluir">Excluir</button>
                            </form>
                        </div>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" style="text-align: center;">Nenhum membro encontrado.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <!-- Paginação -->
{#        {% if is_paginated %}#}
{#            <div style="font-size: 0.9rem" class="pagination" style="margin-top: 20px; text-align: center;">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;#}
{#                        Anterior</a>#}
{#                {% endif %}#}
{##}
{#                <span style="margin: 0 10px;">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>#}
{##}
{#                {% if page_obj.has_next %}#}
{#                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;#}
{#                        Anterior</a>#}
{#                {% endif %}#}
{#            </div>#}
{#        {% endif %}#}
    </div>
{% endblock %}

sistemahorista/templates/sistemahorista/tela_inicial_vazia.html
{%extends "global/base.html"%}

{%block content%}

{%endblock content%}